# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            vtos
tagline:          "Veru Teatru di l'Ora Scura"
url:              http://127.0.0.1:4000
baseurl:          /

author:
  name:           "Bosco M."
  url:            https://twitter.com/mdo

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"